# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db55f6f6af2652f6f1d59a0cbb563822445ef00974c6da4b14653e9abdc65056f380716116f21304c1740b61b6f4367c9e666da60327fa23df8db39404c71074

test:
  secret_key_base: 3a272359d165ac20d60de79cd28a0491c9d8d3d0975b8dd3e8634460252893bb26aab2f3889e11e89d3ae02d7aa14387d59b5f9dfb477ed4c89ded1bf56208f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
